import { Product } from './types';

export const categories = ['All', 'Home', 'Electronics', 'Clothing', 'Accessories'];

export const productTypes = ['All', 'Audio', 'Peripherals', 'Apparel', 'Innerwear', 'Outerwear', 'Footwear', 'Kitchen', 'Decor', 'Furniture', 'Bags', 'Eyewear', 'Watches', 'Laptops', 'Gaming', 'Mobile', 'Gadgets', 'Appliances', 'Cables'];

export const products: Product[] = ([
  {
    id: '1',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    inventory: 3,
    brand: 'Sony',
    model: 'WH-1000XM5',
    variant: 'Midnight Blue',
    description: 'Premium over-ear headphones with industry-leading active noise cancellation and 30-hour battery life.',
    price: 349.99,
    category: 'Electronics',
    type: 'Audio',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 7,
    sustainabilityGrade: 'B',
    warrantyInfo: '2 Years Manufacturer Warranty',
    aiSummary: 'Perfect match for commuting and deep focus. Verified authentic. Highest rated noise cancellation in its class.'
  },
  {
    id: '2',
    name: 'Keychron Q1 Pro Mechanical Keyboard',
    inventory: 0,
    brand: 'Keychron',
    model: 'Q1 Pro',
    variant: 'Carbon Black (Brown Switches)',
    description: 'Wireless custom mechanical keyboard with a 75% layout, QMK/VIA support, and a full aluminum CNC machined body.',
    price: 199.00,
    category: 'Electronics',
    type: 'Peripherals',
    inStock: false,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    trustScore: 94,
    repairabilityScore: 10,
    sustainabilityGrade: 'B',
    warrantyInfo: '1 Year Limited Warranty',
    aiSummary: 'Excellent for programming and typing. Highly repairable with hot-swappable switches and open-source firmware.'
  },
  {
    id: '3',
    name: 'Patagonia Better Sweater Fleece Jacket',
    brand: 'Patagonia',
    model: 'Better Sweater 1/4-Zip',
    variant: 'Stonewash',
    description: 'A warm, low-bulk quarter-zip jacket made of soft, sweater-knit recycled polyester fleece.',
    price: 139.00,
    category: 'Clothing',
    type: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    trustScore: 99,
    repairabilityScore: 9,
    sustainabilityGrade: 'A',
    warrantyInfo: 'Ironclad Guarantee (Lifetime)',
    aiSummary: 'Top sustainability pick. Made with 100% recycled polyester. Excellent repair program offered by manufacturer.',
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: '4',
    name: 'Chemex Classic Series Pour-Over Glass Coffeemaker',
    brand: 'Chemex',
    model: 'Classic Series (8-Cup)',
    variant: 'Glass with Wood Collar',
    description: 'Elegant, hour-glass shaped coffee maker made of high quality, heat resistant glass. Includes polished wood collar with leather tie.',
    price: 49.95,
    category: 'Home',
    type: 'Kitchen',
    image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    trustScore: 96,
    repairabilityScore: 2,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Defect Warranty',
    aiSummary: 'Ideal for artisanal brewing. Zero plastic parts. Note: Fragile, poor repairability if dropped, but individual components (collar, tie) are replaceable.'
  },
  {
    id: '5',
    name: 'Herman Miller Aeron Ergonomic Office Chair',
    brand: 'Herman Miller',
    model: 'Aeron',
    variant: 'Size B - Graphite',
    description: 'The iconic ergonomic office chair, designed to provide unparalleled support and comfort for long hours of sitting.',
    price: 1275.00,
    category: 'Home',
    type: 'Furniture',
    image: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    trustScore: 100,
    repairabilityScore: 9,
    sustainabilityGrade: 'A',
    warrantyInfo: '12-Year Manufacturer Warranty',
    aiSummary: 'The gold standard for office ergonomics. Exceptionally high initial cost, but long-term value is unmatched due to durability and 12-year warranty. Highly repairable.'
  },
  {
    id: '6',
    name: 'Peak Design Everyday Backpack',
    brand: 'Peak Design',
    model: 'Everyday Backpack V2',
    variant: '20L - Charcoal',
    description: 'A versatile, durable, and highly accessible backpack designed for everyday carry and camera gear.',
    price: 279.95,
    category: 'Accessories',
    type: 'Bags',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    trustScore: 97,
    repairabilityScore: 8,
    sustainabilityGrade: 'B',
    warrantyInfo: 'Lifetime Warranty',
    aiSummary: 'Extremely durable and weather-proof. Modular internal dividers make it highly versatile. Backed by a lifetime warranty.'
  },
  {
    id: '7',
    name: 'Ray-Ban Original Wayfarer Classic',
    brand: 'Ray-Ban',
    model: 'Original Wayfarer Classic (RB2140)',
    variant: 'Black Frame / Green Classic G-15 Lenses',
    description: 'The most recognizable style in the history of sunglasses, featuring a classic black frame and green lenses.',
    price: 171.00,
    category: 'Accessories',
    type: 'Eyewear',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    trustScore: 91,
    repairabilityScore: 6,
    sustainabilityGrade: 'C',
    warrantyInfo: '2 Year Limited Warranty',
    aiSummary: 'Timeless design with excellent optical clarity. Lenses are replaceable, though frame repairs can be difficult.'
  },
  {
    id: '8',
    name: 'Apple MacBook Air M3',
    brand: 'Apple',
    model: 'MacBook Air (15-inch, M3)',
    variant: 'Midnight - 16GB RAM, 512GB SSD',
    description: 'Supercharged by M3, the 15-inch MacBook Air features a liquid retina display, 18 hours of battery life, and a fanless design.',
    price: 1499.00,
    category: 'Electronics',
    type: 'Laptops',
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    trustScore: 99,
    repairabilityScore: 4,
    sustainabilityGrade: 'B',
    warrantyInfo: '1 Year Limited Warranty (AppleCare+ Available)',
    aiSummary: 'Best overall laptop for general use. Exceptional battery life and performance. Poor repairability due to soldered components.'
  },
  {
    id: '9',
    name: 'Sony PlayStation 5 Base Edition',
    brand: 'Sony',
    model: 'PlayStation 5',
    variant: 'Disc Edition',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    price: 499.99,
    category: 'Electronics',
    type: 'Gaming',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Black_and_white_Playstation_5_base_edition_with_controller.png/960px-Black_and_white_Playstation_5_base_edition_with_controller.png',
    rating: 4.8,
    trustScore: 99,
    repairabilityScore: 7,
    sustainabilityGrade: 'C',
    warrantyInfo: '1 Year Manufacturer Warranty',
    aiSummary: 'The definitive next-gen console experience. Outstanding exclusive game library. Image correctly verified as the Base (Disc) Edition.'
  },
  {
    id: '10',
    name: 'Nintendo Switch',
    brand: 'Nintendo',
    model: 'Switch',
    variant: 'Neon Blue / Neon Red Joy-Con',
    description: 'Play at home on the TV or on-the-go with a vibrant 6.2-inch screen. Includes Joy-Con (L) and Joy-Con (R) controllers.',
    price: 299.99,
    category: 'Electronics',
    type: 'Gaming',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Nintendo-Switch-wJoyCons-BlRd-Standing-FL.png/960px-Nintendo-Switch-wJoyCons-BlRd-Standing-FL.png',
    rating: 4.7,
    trustScore: 98,
    repairabilityScore: 6,
    sustainabilityGrade: 'B',
    warrantyInfo: '1 Year Manufacturer Warranty',
    aiSummary: 'Highly versatile hybrid console. Excellent for family gaming and portability. Verified image correctly matches the Neon Joy-Con model.'
  },
  {
    id: '11',
    name: 'Samsung Galaxy S24',
    brand: 'Samsung',
    model: 'Galaxy S24',
    variant: 'Amber Yellow - 256GB',
    description: 'Welcome to the era of mobile AI. The Galaxy S24 empowers you with new AI features, a stunning 6.2-inch FHD+ AMOLED display, and a powerful camera system.',
    price: 799.00,
    category: 'Electronics',
    type: 'Mobile',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Samsung_Galaxy_S24%2C_Sperrbildschirm.JPG/960px-Samsung_Galaxy_S24%2C_Sperrbildschirm.JPG',
    rating: 4.6,
    trustScore: 97,
    repairabilityScore: 8,
    sustainabilityGrade: 'B',
    warrantyInfo: '1 Year Standard Warranty',
    aiSummary: 'Excellent compact Android flagship. Integrated AI features are highly rated. Verified image confirms S24 base model design language.'
  },
  {
    id: '12',
    name: 'Apple Watch Series 10',
    brand: 'Apple',
    model: 'Watch Series 10',
    variant: 'Silver Aluminum Case',
    description: 'The thinnest Apple Watch yet with the biggest display. Features advanced health sensors, faster charging, and a sleek aluminum design.',
    price: 399.00,
    category: 'Electronics',
    type: 'Gadgets',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Apple_Watch_Series_10.jpg/960px-Apple_Watch_Series_10.jpg',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 3,
    sustainabilityGrade: 'A',
    warrantyInfo: '1 Year Limited Warranty',
    aiSummary: 'Top-tier smartwatch for iOS users. Carbon neutral case and band combinations available. Low repairability.'
  },
  {
    id: '13',
    name: 'Apple AirPods Pro',
    brand: 'Apple',
    model: 'AirPods Pro',
    variant: 'White with MagSafe Case',
    description: 'Active Noise Cancellation for immersive sound. Transparency mode for hearing the world around you. Sweat and water resistant.',
    price: 249.00,
    category: 'Electronics',
    type: 'Audio',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/AirPods_Pro_3_with_case.jpg/960px-AirPods_Pro_3_with_case.jpg',
    rating: 4.7,
    trustScore: 99,
    repairabilityScore: 1,
    sustainabilityGrade: 'C',
    warrantyInfo: '1 Year Limited Warranty',
    aiSummary: 'Excellent integration with Apple ecosystem. Zero repairability; batteries cannot be replaced without destroying the unit.'
  },
  {
    id: '14',
    name: 'Nike Air Force 1 \'07',
    brand: 'Nike',
    model: 'Air Force 1',
    variant: 'White on White',
    description: 'The radiance lives on in the Nike Air Force 1 \'07, the b-ball icon that puts a fresh spin on what you know best.',
    price: 115.00,
    category: 'Clothing',
    type: 'Footwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Nike_air_Force_1_white_on_white.jpg/960px-Nike_air_Force_1_white_on_white.jpg',
    rating: 4.8,
    trustScore: 99,
    repairabilityScore: 6,
    sustainabilityGrade: 'C',
    warrantyInfo: '60-Day Return Policy',
    aiSummary: 'A timeless sneaker staple. Very durable but difficult to clean once deeply stained. High authenticity verification.',
    sizes: ['7', '8', '9', '10', '11', '12']
  },
  {
    id: '15',
    name: 'Converse Chuck Taylor All Star',
    brand: 'Converse',
    model: 'Chuck Taylor All Star',
    variant: 'High Top Black',
    description: 'Created in 1917, the Chuck Taylor All Star sneaker is the original basketball shoe. Its use has changed over the years, but it’s still perfect in its simplicity.',
    price: 65.00,
    category: 'Clothing',
    type: 'Footwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Black_Converse_sneakers.JPG/960px-Black_Converse_sneakers.JPG',
    rating: 4.6,
    trustScore: 97,
    repairabilityScore: 7,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Return Policy',
    aiSummary: 'Classic design, easily washable and long-lasting canvas. verified image confirms classic black high-top styling.',
    sizes: ['7', '8', '9', '10', '11', '12']
  },
  {
    id: '16',
    name: 'Rolex Submariner Date',
    brand: 'Rolex',
    model: 'Submariner',
    variant: 'Oyster, 41 mm, Oystersteel',
    description: 'The Rolex Submariner Date in Oystersteel with a Cerachrom bezel insert in black ceramic and a black dial with large luminescent hour markers.',
    price: 10250.00,
    category: 'Accessories',
    type: 'Watches',
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Rolex-Submariner.jpg',
    rating: 4.9,
    trustScore: 100,
    repairabilityScore: 9,
    sustainabilityGrade: 'A',
    warrantyInfo: '5-Year International Guarantee',
    aiSummary: 'High-value heirloom piece. Servicing is expensive but ensures lifetime operation. Image is verified authentic Submariner.'
  },
  {
    id: '17',
    name: 'Casio F-91W-1',
    brand: 'Casio',
    model: 'F-91W',
    variant: 'Black Resin',
    description: 'A tried and true style great for casual wear. With its daily alarm, hourly time signal and auto calendar, you\'ll never need to worry about missing an appointment again.',
    price: 22.95,
    category: 'Accessories',
    type: 'Watches',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Casio_F-91W_5051.jpg/960px-Casio_F-91W_5051.jpg',
    rating: 4.9,
    trustScore: 99,
    repairabilityScore: 5,
    sustainabilityGrade: 'B',
    warrantyInfo: '1-Year Warranty',
    aiSummary: 'The ultimate budget digital watch. Battery lasts for years. Image accurately depicts the iconic classic resin model.'
  },
  {
    id: '18',
    name: 'Hermès Birkin 25',
    brand: 'Hermès',
    model: 'Birkin',
    variant: 'Pink Togo Leather, Palladium Hardware',
    description: 'The Birkin bag is a personal heritage. Crafted from luxurious Togo leather and accented with palladium hardware, it is an icon of luxury.',
    price: 18500.00,
    category: 'Accessories',
    type: 'Bags',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Pink_Birkin_bag.jpg/960px-Pink_Birkin_bag.jpg',
    rating: 5.0,
    trustScore: 100,
    repairabilityScore: 10,
    sustainabilityGrade: 'A',
    warrantyInfo: 'Lifetime Artisan Repair (At Cost)',
    aiSummary: 'Extremely rare and highly counterfeited. Our platform provides 100% authenticity verification. Image matches Pink Togo leather.'
  },
  {
    id: '19',
    name: 'Levi\'s 501 Original Fit Jeans',
    brand: 'Levi\'s',
    model: '501 Original',
    variant: 'Medium Stonewash',
    description: 'The original blue jean since 1873. The original straight fit jean, featuring the iconic straight fit and signature button fly.',
    price: 79.50,
    category: 'Clothing',
    type: 'Apparel',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Jeans.jpg',
    rating: 4.7,
    trustScore: 95,
    repairabilityScore: 8,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Classic straight leg jeans. Extremely durable denim with high repairability.',
    sizes: ['30x30', '32x30', '32x32', '34x32', '36x32']
  },
  {
    id: '20',
    name: 'Adidas Stan Smith',
    brand: 'Adidas',
    model: 'Stan Smith',
    variant: 'Cloud White / Green',
    description: 'The timeless appeal of the Stan Smith shoe, with its crisp, clean style and signature green heel tab.',
    price: 100.00,
    category: 'Clothing',
    type: 'Footwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Stan_Smith_white_and_green.png',
    rating: 4.6,
    trustScore: 94,
    repairabilityScore: 4,
    sustainabilityGrade: 'C',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'A classic silhouette that pairs well with anything. Bonded sole lowers repairability.',
    sizes: ['7', '8', '9', '10', '11', '12']
  },
  {
    id: '21',
    name: 'Le Creuset Signature Round Dutch Oven',
    brand: 'Le Creuset',
    model: 'Signature Round 5.5 qt',
    variant: 'Cerise',
    description: 'The iconic Le Creuset Dutch oven is indispensable in the kitchens of home cooks and professional chefs alike. Expertly crafted from enameled cast iron.',
    price: 420.00,
    category: 'Home',
    type: 'Kitchen',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/20151003%EB%83%84%EB%B9%84RX10DSC03006.jpg/960px-20151003%EB%83%84%EB%B9%84RX10DSC03006.jpg',
    rating: 4.9,
    trustScore: 100,
    repairabilityScore: 10,
    sustainabilityGrade: 'A',
    warrantyInfo: 'Lifetime Limited Warranty',
    aiSummary: 'A buy-it-for-life item. Practically indestructible. Enameled coating can chip if abused, but the pot remains functional.'
  },
  {
    id: '22',
    name: 'Numatic Henry Vacuum Cleaner',
    brand: 'Numatic',
    model: 'HVR160',
    variant: 'Red/Black',
    description: 'Henry brings professional cleaning to all and is packed full of innovative features. Henry’s cable and storage rewind system is a work of art.',
    price: 179.99,
    category: 'Home',
    type: 'Appliances',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg/960px-Numatic_Henry_vacuum_cleaner_%283308986870%29_%28cropped%29.jpg',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 9,
    sustainabilityGrade: 'B',
    warrantyInfo: '2-Year Commercial Warranty',
    aiSummary: 'Legendary durability and repairability. The smiling face hides a commercial-grade motor built to last decades.'
  },
  {
    id: '23',
    name: 'The North Face Retro Nuptse Jacket',
    brand: 'The North Face',
    model: '1996 Retro Nuptse',
    variant: 'Black',
    description: 'Built for mountain- and city-life, this retro Nuptse jacket has a boxy silhouette, original shiny ripstop fabric, iconic oversize baffles and stowable hood.',
    price: 330.00,
    category: 'Clothing',
    type: 'Outerwear',
    image: 'https://images.unsplash.com/photo-1559551409-dadc959f76b8?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    trustScore: 98,
    repairabilityScore: 7,
    sustainabilityGrade: 'C',
    warrantyInfo: 'Limited Lifetime Warranty',
    aiSummary: 'Classic puffer jacket with high warmth-to-weight ratio. Very popular streetwear item.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: '24',
    name: 'Patagonia Baggies Shorts',
    brand: 'Patagonia',
    model: 'Baggies 5"',
    variant: 'Forge Grey',
    description: 'Rugged, multifunctional shorts designed for use in and out of the water, made of quick-drying 100% recycled nylon.',
    price: 65.00,
    category: 'Clothing',
    type: 'Apparel',
    image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    trustScore: 99,
    repairabilityScore: 8,
    sustainabilityGrade: 'A',
    warrantyInfo: 'Ironclad Guarantee (Lifetime)',
    aiSummary: 'Extremely durable and versatile summer shorts. Sustainable materials.',
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: '25',
    name: 'Calvin Klein Cotton Classics Boxer Briefs',
    brand: 'Calvin Klein',
    model: 'Cotton Classics',
    variant: 'Black 3-Pack',
    description: 'Classic, everyday boxer briefs made from soft, breathable cotton with a comfortable elastic waistband.',
    price: 42.50,
    category: 'Clothing',
    type: 'Apparel',
    image: 'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    trustScore: 95,
    repairabilityScore: 2,
    sustainabilityGrade: 'C',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Comfortable standard innerwear. Quality is consistent but elastic can wear out over years of washing.',
    sizes: ['S', 'M', 'L', 'XL']
  },
  {
    id: '26',
    name: 'Champion Reverse Weave Hoodie',
    brand: 'Champion',
    model: 'Reverse Weave',
    variant: 'Silver Grey',
    description: 'The King of Sweatshirts. Cut on the cross-grain to resist vertical shrinkage, so the length stays true to size.',
    price: 60.00,
    category: 'Clothing',
    type: 'Apparel',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    trustScore: 96,
    repairabilityScore: 6,
    sustainabilityGrade: 'C',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Heavyweight and very durable hoodie. Resists shrinking well.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL']
  },
  {
    id: '27',
    name: 'LG C3 65-inch 4K OLED TV',
    brand: 'LG',
    model: 'C3',
    variant: '65-inch',
    description: 'The OLED evo C-series is powered by the a9 AI Processor Gen6 for beautiful picture and performance.',
    price: 1599.99,
    category: 'Electronics',
    type: 'Gadgets',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Panasonic_TX-P55ST60E_late_era_plasma_TV.jpg/960px-Panasonic_TX-P55ST60E_late_era_plasma_TV.jpg',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 4,
    sustainabilityGrade: 'C',
    warrantyInfo: '1-Year Limited Warranty',
    aiSummary: 'Top-tier picture quality with infinite contrast. Vulnerable to burn-in over extreme long-term use. Panel replacement is expensive.'
  },
  {
    id: '28',
    name: 'DJI Mini 3 Pro Drone',
    brand: 'DJI',
    model: 'Mini 3 Pro',
    variant: 'Fly More Combo',
    description: 'The mini-sized, mega-capable DJI Mini 3 Pro is as powerful as it is portable. Weighing less than 249 g.',
    price: 859.00,
    category: 'Electronics',
    type: 'Gadgets',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Quadcopter_camera_drone_in_flight.jpg/960px-Quadcopter_camera_drone_in_flight.jpg',
    rating: 4.7,
    trustScore: 97,
    repairabilityScore: 5,
    sustainabilityGrade: 'C',
    warrantyInfo: '1-Year Warranty',
    aiSummary: 'Excellent entry-level professional drone. Difficult to repair by users, often requires sending back to manufacturer.'
  },
  {
    id: '29',
    name: 'Apple iPad Pro 12.9-inch (M2)',
    brand: 'Apple',
    model: 'iPad Pro',
    variant: '12.9-inch, Wi-Fi, 256GB',
    description: 'The ultimate iPad experience with the most advanced technology, featuring the brilliant Liquid Retina XDR display and the M2 chip.',
    price: 1199.00,
    category: 'Electronics',
    type: 'Mobile',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Wikipedia_on_iPad_Pro.jpg/960px-Wikipedia_on_iPad_Pro.jpg',
    rating: 4.9,
    trustScore: 100,
    repairabilityScore: 3,
    sustainabilityGrade: 'B',
    warrantyInfo: '1-Year Limited Warranty',
    aiSummary: 'Best in class tablet. Highly restricted repairability; screen and battery replacements are best done by Apple.',
    sizes: ['128GB', '256GB', '512GB', '1TB']
  },
  {
    id: '30',
    name: 'Samsung Galaxy Watch 6 Classic',
    brand: 'Samsung',
    model: 'Galaxy Watch 6 Classic',
    variant: '47mm, Black',
    description: 'Meet the smartwatch that looks like a watch, featuring a rotating bezel and a brilliant display, plus advanced health and fitness tracking.',
    price: 399.99,
    category: 'Accessories',
    type: 'Watches',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Samsung_Galaxy_Watch.jpg/960px-Samsung_Galaxy_Watch.jpg',
    rating: 4.6,
    trustScore: 95,
    repairabilityScore: 5,
    sustainabilityGrade: 'C',
    warrantyInfo: '1-Year Warranty',
    aiSummary: 'Feature-rich smartwatch with rotating bezel. Battery replacement is possible but compromises water resistance if not done professionally.'
  },
  {
    id: '31',
    name: 'Ray-Ban Aviator Classic',
    brand: 'Ray-Ban',
    model: 'Aviator Classic',
    variant: 'Gold Frame, Green Lenses',
    description: 'Currently one of the most iconic sunglass models in the world, originally designed for U.S. aviators in 1937.',
    price: 163.00,
    category: 'Accessories',
    type: 'Eyewear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Face_detail%2C_Lt_Mike_Hunter_2_%28cropped%29.jpg/960px-Face_detail%2C_Lt_Mike_Hunter_2_%28cropped%29.jpg',
    rating: 4.7,
    trustScore: 98,
    repairabilityScore: 8,
    sustainabilityGrade: 'B',
    warrantyInfo: '2-Year Warranty',
    aiSummary: 'Timeless design. Lenses and nose pads are easily replaceable at most opticians.'
  },
  {
    id: '32',
    name: 'Everyday Canvas Tote Bag',
    brand: 'Bellroy',
    model: 'City Tote',
    variant: 'Navy Blue',
    description: 'A versatile, durable canvas tote bag perfect for daily errands, work commutes, or weekend trips.',
    price: 45.00,
    category: 'Accessories',
    type: 'Bags',
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Totebag.jpg',
    rating: 4.5,
    trustScore: 92,
    repairabilityScore: 9,
    sustainabilityGrade: 'A',
    warrantyInfo: '3-Year Warranty',
    aiSummary: 'Simple and practical. Fabric can be easily patched or sewn if torn. Biodegradable if 100% cotton.'
  },
  {
    id: '33',
    name: 'Timbuk2 Classic Messenger Bag',
    brand: 'Timbuk2',
    model: 'Classic',
    variant: 'Black',
    description: 'The original Timbuk2 messenger bag. Durable, organized, and iconic.',
    price: 109.00,
    category: 'Accessories',
    type: 'Bags',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Timbuk2_custom-made_messenger_bag_%E2%80%9EDeeDog%E2%80%9C.JPG/960px-Timbuk2_custom-made_messenger_bag_%E2%80%9EDeeDog%E2%80%9C.JPG',
    rating: 4.8,
    trustScore: 97,
    repairabilityScore: 8,
    sustainabilityGrade: 'B',
    warrantyInfo: 'Lifetime Warranty',
    aiSummary: 'A durable and versatile messenger bag suitable for daily commuting.'
  },
  {
    id: '34',
    name: 'Classic Leather Belt',
    brand: 'Generic',
    model: 'Classic',
    variant: 'Brown',
    description: 'A genuine leather belt featuring a classic buckle design for everyday wear.',
    price: 35.00,
    category: 'Clothing',
    type: 'Apparel',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Germany_Belt-and-Buckle-02.jpg/960px-Germany_Belt-and-Buckle-02.jpg',
    rating: 4.5,
    trustScore: 92,
    repairabilityScore: 6,
    sustainabilityGrade: 'C',
    warrantyInfo: '1-Year Warranty',
    aiSummary: 'Standard leather belt with a timeless design.',
    sizes: ['32', '34', '36', '38', '40']
  },
  {
    id: '35',
    name: 'Apple iPhone 14',
    brand: 'Apple',
    model: 'iPhone 14',
    variant: 'Midnight, 128GB',
    description: 'The iPhone 14 features a durable design, the A15 Bionic chip, and a huge leap in low-light camera performance.',
    price: 699.00,
    category: 'Electronics',
    type: 'Mobile',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/IPhone_14_vector.svg/960px-IPhone_14_vector.svg.png',
    rating: 4.8,
    trustScore: 99,
    repairabilityScore: 6,
    sustainabilityGrade: 'B',
    warrantyInfo: '1-Year Limited Warranty',
    aiSummary: 'Reliable and fast smartphone with a great camera. Repairability is improving but still challenging.'
  },
  {
    id: '36',
    name: 'Apple 20W USB-C Power Adapter',
    brand: 'Apple',
    model: '20W Power Adapter',
    variant: 'White',
    description: 'The Apple 20W USB-C Power Adapter offers fast, efficient charging at home, in the office, or on the go.',
    price: 19.00,
    category: 'Electronics',
    type: 'Gadgets',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/1.webp',
    rating: 4.9,
    trustScore: 100,
    repairabilityScore: 2,
    sustainabilityGrade: 'C',
    warrantyInfo: '1-Year Limited Warranty',
    aiSummary: 'Essential charger for fast charging modern iPhones. Not designed to be repaired.'
  },
  {
    id: '37',
    name: 'Apple MagSafe Battery Pack',
    brand: 'Apple',
    model: 'MagSafe Battery Pack',
    variant: 'White',
    description: 'Attaching the MagSafe Battery Pack is a snap. Its compact, intuitive design makes on-the-go charging easy.',
    price: 99.00,
    category: 'Electronics',
    type: 'Gadgets',
    image: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/1.webp',
    rating: 4.4,
    trustScore: 96,
    repairabilityScore: 1,
    sustainabilityGrade: 'D',
    warrantyInfo: '1-Year Limited Warranty',
    aiSummary: 'Convenient wireless power bank. Battery is enclosed and impossible to service.'
  },
  {
    id: '38',
    name: 'Anker USB-C to USB-C Cable',
    brand: 'Anker',
    model: 'Powerline III',
    variant: '6ft, Black',
    description: 'A durable and reliable USB-C cable supporting fast charging and high-speed data transfer.',
    price: 15.99,
    category: 'Electronics',
    type: 'Cables',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/USB-C_plug%2C_focus_stacked.jpg/960px-USB-C_plug%2C_focus_stacked.jpg',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 3,
    sustainabilityGrade: 'C',
    warrantyInfo: 'Lifetime Warranty',
    aiSummary: 'Extremely durable braided cable. If it fails, it is replaced rather than repaired.'
  },
  {
    id: '39',
    name: 'Women\'s Leather Handbag',
    brand: 'Generic',
    model: 'Tote',
    variant: 'Blue',
    description: 'A spacious and stylish blue leather handbag suitable for daily use or travel.',
    price: 79.99,
    category: 'Accessories',
    type: 'Bags',
    image: 'https://cdn.dummyjson.com/product-images/womens-bags/blue-women\'s-handbag/1.webp',
    rating: 4.6,
    trustScore: 94,
    repairabilityScore: 7,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Stylish everyday handbag. Straps and hardware can be repaired by a cobbler.'
  },
  {
    id: '40',
    name: 'Essential Cotton Undershirt 3-Pack',
    brand: 'ComfortBasics',
    model: 'Crew Neck',
    variant: 'White',
    description: 'Ultra-soft, breathable 100% combed cotton undershirts. Features a tag-less design and lay-flat collar that keeps its shape wash after wash.',
    price: 24.00,
    category: 'Clothing',
    type: 'Innerwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/d/da/Leipzig2012.jpg',
    rating: 4.7,
    trustScore: 95,
    repairabilityScore: 3,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'A reliable staple. The 100% cotton construction offers great breathability and comfort.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    fitDetails: 'Classic fit with extra length to stay tucked in.',
    sizeGuide: 'Chest (inches): S: 34-36, M: 38-40, L: 42-44, XL: 46-48, XXL: 50-52'
  },
  {
    id: '41',
    name: 'Seamless Microfiber Bralette',
    brand: 'LoungeWear',
    model: 'Seamless',
    variant: 'Nude',
    description: 'A wire-free, seamless bralette offering gentle support and ultimate comfort. Perfect for lounging or everyday wear under t-shirts.',
    price: 32.00,
    category: 'Clothing',
    type: 'Innerwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Modern_bra_fullcup.jpg/960px-Modern_bra_fullcup.jpg',
    rating: 4.8,
    trustScore: 98,
    repairabilityScore: 2,
    sustainabilityGrade: 'C',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Highly rated for comfort. The seamless design makes it invisible under most clothing.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fitDetails: 'Snug, stretchy fit that adapts to your shape.',
    sizeGuide: 'Band Size (inches): XS: 30, S: 32, M: 34, L: 36, XL: 38. Fits cup sizes A-C best.'
  },
  {
    id: '42',
    name: 'Performance Boxer Briefs',
    brand: 'ActiveFit',
    model: 'Pro-Cool',
    variant: 'Black/Grey 2-Pack',
    description: 'Moisture-wicking, anti-odor boxer briefs designed for active lifestyles. Features a supportive pouch and a waistband that won\'t roll down.',
    price: 38.00,
    category: 'Clothing',
    type: 'Innerwear',
    image: 'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    trustScore: 99,
    repairabilityScore: 2,
    sustainabilityGrade: 'C',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'Excellent for workouts. The synthetic blend wicks sweat efficiently and prevents chafing.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    fitDetails: 'Athletic fit with a 6-inch inseam. Fits close to the body.',
    sizeGuide: 'Waist (inches): S: 28-30, M: 32-34, L: 36-38, XL: 40-42, XXL: 44-46'
  },
  {
    id: '43',
    name: 'Lace Trim Bikini Panties',
    brand: 'Elegance',
    model: 'Everyday Lace',
    variant: 'Blush Pink',
    description: 'Soft modal blend bikini panties with delicate lace trim. Offers a comfortable, mid-rise fit with moderate back coverage.',
    price: 18.00,
    category: 'Clothing',
    type: 'Innerwear',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Lingerie.jpg/960px-Lingerie.jpg',
    rating: 4.6,
    trustScore: 94,
    repairabilityScore: 1,
    sustainabilityGrade: 'B',
    warrantyInfo: '30-Day Returns',
    aiSummary: 'A good balance of comfort and style. The modal fabric is very soft against the skin.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    fitDetails: 'Mid-rise bikini cut, sitting comfortably at the hips.',
    sizeGuide: 'Hips (inches): XS: 34-35, S: 36-37, M: 38-39, L: 40-41, XL: 42-43'
  }
] as Product[]).map((product: Product) => {
  const priceHistory = [];
  let currentPrice = product.price;
  for (let i = 30; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    priceHistory.push({
      date: d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      price: Number(currentPrice.toFixed(2))
    });
    // Add small random fluctuation, but end up at the current price
    currentPrice = currentPrice * (1 + (Math.random() * 0.04 - 0.02)); 
  }
  // Ensure the last price is the exact current price
  priceHistory[priceHistory.length - 1].price = product.price;
  return { ...product, priceHistory };
});
